input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Тут можно фильтровать поля, например:
  mutate {
    rename => { "old_field" => "new_field" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}