spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${REALM_URL}
  application:
    name: item-service
  datasource:
    url: jdbc:postgresql://localhost:5432/item_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
