spring:
  application:
    name: review-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer




  datasource:
    url: jdbc:postgresql://localhost:5432/review_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
